#!/bin/bash

if [ `/usr/bin/id -u` != "0" ]; then
  echo "Please run the script as root!"
else
  apt install -y p7zip
  wget https://github.com/OJ/gobuster/releases/download/v2.0.1/gobuster-linux-amd64.7z -O /tmp/gobuster-linux-amd64.7z
  7z x /tmp/gobuster-linux-amd64.7z -o/tmp
  mv /tmp/gobuster-linux-amd64/gobuster /opt/gobuster
  chmod +x /opt/gobuster
  ln -s /opt/gobuster /usr/bin/gobuster
  rm -rf /tmp/gobuster-linux-amd64 /tmp/gobuster-linux-amd64.7z
fi
