#!/bin/bash

# This script installs gobuster from an ubuntu repository server

if [ `/usr/bin/id -u` != "0" ]; then
  echo "Please run the script as root!"
else
  wget -q http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gobuster/gobuster_1.4.1-1_amd64.deb
  dpkg -i gobuster_1.4.1-1_amd64.deb
  rm gobuster_1.4.1-1_amd64.deb
  apt install -f -y
fi
